//
//  HomePresenter.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomePresenter {

    // MARK: - Private properties -

    private unowned let view: HomeViewInterface
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface
    
    // MARK: - Open properties -

    var repositories: [RepoModel]? {
        didSet {
            repositories?.sort(by: >)
            view.updateView()
        }
    }
    
    // MARK: - Lifecycle -

    init(view: HomeViewInterface, interactor: HomeInteractorInterface, wireframe: HomeWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
    func viewDidLoad() {
        view.setViewTitle("GitHubFinder")
    }
    
    func searchBarSearchButtonClicked(searchText: String?) {
        guard let text = searchText else { return }
        interactor.searchRepositoriesWith(text: text, completion: { repositories, error in
            if error == nil {
                self.repositories = repositories?.items
            }
        })
    }
    
    func didSelectRowAtIndexPath(_ indexPath: IndexPath) {
        wireframe.navigate(to: .details(repositories?[indexPath.row]))
    }
}
