//
//  HomeViewController.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: BaseViewController {

    // MARK: - Public properties -
    @IBOutlet weak var tableView: BaseTableView! {
        didSet {
            tableView.basicSettingsWith(self)
            tableView.register(UINib(nibName: GitTableViewCell.cellID, bundle: nil), forCellReuseIdentifier: GitTableViewCell.cellID)
        }
    }
    
    private let searchController = BaseSearchController(searchResultsController: nil)
    
    var presenter: HomePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        setupSearchController()
    }
    
    // MARK: - Private -
    private func setupSearchController() {
        navigationItem.searchController = searchController
        searchController.searchBar.delegate = self
        searchController.delegate = self
    }
}

// MARK: - HomeViewInterface -

extension HomeViewController: HomeViewInterface {
    func updateView() {
        tableView.reloadDataOnMainQueue()
    }
    
    func setViewTitle(_ title: String?) {
        self.title = title
    }
}

// MARK: - UITableViewDataSource -

extension HomeViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.repositories?.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        if let cell = tableView.dequeueReusableCell(withIdentifier: GitTableViewCell.cellID, for: indexPath) as? GitTableViewCell {
            
            if let model = presenter.repositories?[indexPath.row] {
                cell.gonfigureBy(repo: model)
            }
            
            return cell
        }
        
        return UITableViewCell()
    }
}

// MARK: - UITableViewDelegate -

extension HomeViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        presenter.didSelectRowAtIndexPath(indexPath)
    }
}

//MARK: - UISearchBarDelegate -
extension HomeViewController: UISearchBarDelegate {
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        self.view.endEditing(true)
        presenter.searchBarSearchButtonClicked(searchText: searchBar.text)
    }
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        print(searchText)
    }
}

//MARK: - UISearchControllerDelegate -

extension HomeViewController: UISearchControllerDelegate {
    func willPresentSearchController(_ searchController: UISearchController) {
        
    }
}
