//
//  HomeInterfaces.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
}

protocol HomeViewInterface: ViewInterface {
    func setViewTitle(_ title: String?)
}

protocol HomePresenterInterface: PresenterInterface {
    var repositories: [RepoModel]? { get }
    
    func viewDidLoad()
    func didSelectRowAtIndexPath(_ indexPath: IndexPath)
}

protocol HomeInteractorInterface: InteractorInterface {
}
