//
//  DetailInterfaces.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailWireframeInterface: WireframeInterface {
}

protocol DetailViewInterface: ViewInterface {
}

protocol DetailPresenterInterface: PresenterInterface {
}

protocol DetailInteractorInterface: InteractorInterface {
}
