//
//  DetailsWireframe.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsWireframe: BaseWireframe {

    // MARK: - Module setup -

    init(repo: RepoModel?) {
        let moduleViewController = DetailsViewController()
        super.init(viewController: moduleViewController)

        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, repo: repo)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailsWireframe: DetailsWireframeInterface {
}
