//
//  DetailsViewController.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsViewController: BaseViewController {

    // MARK: - Public properties -

    var presenter: DetailsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.largeTitleDisplayMode = .never
        presenter.viewDidLoad()
    }

}

// MARK: - Extensions -

extension DetailsViewController: DetailsViewInterface {
    func setViewTitle(_ title: String?) {
        self.title = title
    }
}
