//
//  DetailsPresenter.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailsViewInterface
    private let interactor: DetailsInteractorInterface
    private let wireframe: DetailsWireframeInterface

    // MARK: - Open properties -
    var repo: RepoModel?
    
    // MARK: - Lifecycle -

    init(view: DetailsViewInterface, interactor: DetailsInteractorInterface, wireframe: DetailsWireframeInterface, repo: RepoModel?) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.repo = repo
    }
}

// MARK: - Extensions -

extension DetailsPresenter: DetailsPresenterInterface {
    func viewDidLoad() {
        view.setViewTitle("Details")
        view.updateView(text: repo?.detailsDescription)
    }
}
