//
//  DetailInteractor.swift
//  GitHubFinder
//
//  Created by Saul Goodman on 07.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailInteractor {
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
}
